//------------------------------------------------------------------------------
// <auto-generated>
//     Ce code a été généré par un outil.
//     Version du runtime :4.0.30319.42000
//
//     Les modifications apportées à ce fichier peuvent provoquer un comportement incorrect et seront perdues si
//     le code est régénéré.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Majestim._TestBlocks {
    using System;
    
    
    /// <summary>
    ///   Une classe de ressource fortement typée destinée, entre autres, à la consultation des chaînes localisées.
    /// </summary>
    // Cette classe a été générée automatiquement par la classe StronglyTypedResourceBuilder
    // à l'aide d'un outil, tel que ResGen ou Visual Studio.
    // Pour ajouter ou supprimer un membre, modifiez votre fichier .ResX, puis réexécutez ResGen
    // avec l'option /str ou régénérez votre projet VS.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "15.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class Resource1 {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resource1() {
        }
        
        /// <summary>
        ///   Retourne l'instance ResourceManager mise en cache utilisée par cette classe.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("Majestim._TestBlocks.Resource1", typeof(Resource1).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Remplace la propriété CurrentUICulture du thread actuel pour toutes
        ///   les recherches de ressources à l'aide de cette classe de ressource fortement typée.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à 
        ///tr:hover {
        ///    /* background-color	: lavender; */
        ///	box-shadow: 0px 0px 5px 1px gray inset;	
        ///}
        ///
        ///.first-column {
        ///    /* background-color: lightblue; */
        ///    /*padding: 0px;
        ///    vertical-align: bottom;*/
        ///	/* font: &quot;Lucida Console&quot;; */
        ///}
        ///
        ///td {
        ///	font-family: Verdana,sans serif;
        ///	font-size: 12px;
        ///}
        ///
        ///.tv-icon {
        ///    width: 16px;
        ///    border: 1px solid gray;
        ///    border-radius: 2px;
        ///    padding-left: 3px;
        ///    padding-right: 5px;
        ///}
        ///
        ///.tv-no-child {
        ///    width: 16px;
        ///    border: 0px;
        ///}
        ///
        ///.
        /// </summary>
        internal static string tvCss {
            get {
                return ResourceManager.GetString("tvCss", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à &lt;!DOCTYPE html&gt;
        ///&lt;html lang=&quot;en&quot;&gt;
        ///&lt;head&gt;
        ///    &lt;meta name=&quot;viewport&quot; content=&quot;width=device-width, initial-scale=1&quot;&gt;
        ///
        ///    &lt;link rel=&quot;stylesheet&quot; href=&quot;https://maxcdn.bootstrapcdn.com/bootstrap/4.4.1/css/bootstrap.min.css&quot;&gt;
        ///    &lt;link rel=&quot;stylesheet&quot; href=&quot;https://fonts.googleapis.com/icon?family=Material+Icons&quot;&gt;
        ///    &lt;script src=&quot;https://ajax.googleapis.com/ajax/libs/jquery/3.4.1/jquery.min.js&quot;&gt;&lt;/script&gt;
        ///    &lt;script src=&quot;https://cdnjs.cloudflare.com/ajax/libs/popper.js/1.16.0/umd/popper.min.js&quot;&gt;&lt;/script&gt; [le reste de la chaîne a été tronqué]&quot;;.
        /// </summary>
        internal static string tvHtml {
            get {
                return ResourceManager.GetString("tvHtml", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à 
        ///function tvBuild(tvName) {
        ///    var rows = getRows(tvName);
        ///    var parents = [null];
        ///
        ///    // expands
        ///    var onClickAttribute = &quot;onButtonClick();&quot;;
        ///    //var expandInnerHTML = &apos;&lt;td width=&quot;50px&quot;&gt;&lt;span tv-icon=&quot;1&quot; class=&quot;glyphicon glyphicon-triangle-bottom&quot;&gt;&lt;/span&gt;&lt;/td&gt;&apos;;
        ///    //var expandInnerHTML = &apos;&lt;span tv-icon=&quot;1&quot; class=&quot;glyphicon glyphicon-triangle-bottom&quot;&gt;&apos;;
        ///    //var expandInnerHTML = &apos;&lt;span tv-icon class=&quot;btn btn-outline-primary tv-icon&quot;&gt;&lt;/span&gt;&apos;;
        ///    //var expandInnerHTML = &apos;&lt;span tv-icon  [le reste de la chaîne a été tronqué]&quot;;.
        /// </summary>
        internal static string tvJs {
            get {
                return ResourceManager.GetString("tvJs", resourceCulture);
            }
        }
    }
}
